zz:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: zzcoder
    username: zazhi
    password: 123456
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/zzcoder
    host: localhost
    port: 3306
    database: zzcoder
    username: root
    password: 123456